index:
    path:     /
    defaults: { _controller: LearningSymfonyTodolistBundle:Todo:index }

add_new_task:
    path:   /new
    methods: ['POST']
    defaults: { _controller: LearningSymfonyTodolistBundle:Todo:new }
